<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>MedicalStore.KeyGen</AssemblyName>
    <RootNamespace>MedicalStore.KeyGen</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\MedicalStore.Common\MedicalStore.Common.csproj" />
  </ItemGroup>
</Project>
